name: webtk_cad_310_v6
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pytest
  - nbmake
  - ipython
  - ipywidgets
  - matplotlib
  - numpy
  - pandas
  - scipy
  - h5py
  - trimesh
  - trame
  - trame-client
  - trame-server
  - trame-vtk
  - trame-vuetify
  - trame-jupyter-extension
  - pyvista
  - pip:
    - jupyter-cadquery
    - ocp_vscode
    - build123d
    - cadquery
    - pythonocc-core