name: webtk_pvn_dev
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - matplotlib
  - numpy
  - scipy
  - ipykernel
  - ipython
  - ipywidgets
  - jupyter_client
  - pythonocc-core
  - build123d
  - cadquery
  - nlopt==2.10.0
  - trimesh
  - pip:
    - pyvista[jupyter]
    - trame[all]
    - jupyter_cadquery
    - ocp_vscode