from build123d import *
from ocp_vscode import *

set_port(3939)

length = 300.0
width = 50.0
height = 25.0

# ìƒˆë¡œìš´ ìœ„ì¹˜ (ê¸¸ì´ ë°©í–¥ ë¹„ìœ¨)
bow_x = -length * 0.45
mid_x = 0
stern_x = length * 0.35

# ë‹¨ë©´ ìœ„ì¹˜ (Xì¶• ë°©í–¥, bow â†’ mid â†’ stern)
bow_x = -length * 0.45
mid_x = 0
stern_x = length * 0.35

def make_half_ellipse_sketch(w, h, x_pos):
    """
    YZâ€¯í‰ë©´(ë²•ì„ =Xì¶•)ì— ë†“ì¸ ë°˜íƒ€ì›í˜• ë‹¨ë©´Â Face ë°˜í™˜
    w : ë‹¨ë©´ í­  (Y ë°©í–¥ ì „í­)
    h : ë‹¨ë©´ ë†’ì´(Z ë°©í–¥ ì „ê³ )
    x_pos : ë‹¨ë©´ì´ ë†“ì¼ X ì¢Œí‘œ
    """
    r        = w / 2                     # ë°˜ì§€ë¦„ = ë°˜í­
    z_scale  = h / r                     # Zì¶• ìŠ¤ì¼€ì¼(ë°˜íƒ€ì› ë¹„ìœ¨)

    # â–¼ YZ í‰ë©´ì„ ëª…ì‹œì ìœ¼ë¡œ ì§€ì •: x_dir=Yì¶•, normal=Xì¶•
    yz_plane = Plane(
        origin = (x_pos, 0, 0),          # Xì¶• ìœ„ì¹˜ ì¡°ì •
        x_dir  = (0, 1, 0),              # í‰ë©´ì˜ localâ€‘x  â†’ ì „ì—­ Y
        y_dir  = (0, 0, 1),              # í‰ë©´ì˜ localâ€‘y  â†’ ì „ì—­ Z
        z_dir  = (1, 0, 0),              # í‰ë©´ì˜ localâ€‘z  â†’ ì „ì—­ X
        # normal = (1, 0, 0)               # í‰ë©´ ë²•ì„       â†’ ì „ì—­ X
    )

    with BuildSketch(yz_plane) as sk:
        with BuildLine():
            #   â†±--- ì „ì—­ Y ë°©í–¥ ---â†°
            #   (-r,0)â”€â”€â”€â–¶â”€â”€â”€(r,0)   â† í‰ë©´ì˜ localâ€‘xì¶•
            CenterArc(center=(0, 0), radius=r, start_angle=180, arc_size=180)
            Line(( r, 0), (-r, 0))       # ìœ—ë©´ ì§ì„ ìœ¼ë¡œ ë‹«ê¸°
        make_face()

        # Z ë°©í–¥(ì „ì—­ Z = í‰ë©´ì˜ localâ€‘yì¶•)ë§Œ ìŠ¤ì¼€ì¼ â†’ ë°˜íƒ€ì›
        scaled = scale(sk.sketch, (1, 1, z_scale))

    return scaled # ë‹¨ë©´Â Face ë°˜í™˜

# ğŸ’¡ ê° ë‹¨ë©´ ìƒì„±
bow = make_half_ellipse_sketch(width * 0.15, height * 0.4, bow_x)
mid = make_half_ellipse_sketch(width * 1.0, height * 1.0, mid_x)
stern = make_half_ellipse_sketch(width * 0.3, height * 0.5, stern_x)

# show_object(bow)
# show_object(mid)
# show_object(stern)

# ë°° ë°‘ë¶€ë¶„(hull) ë§Œë“¤ê¸°
# with BuildPart() as hull:
#     loft([bow, mid, stern], mode=Mode.ADD)

# show(hull.part)

# ë°° ì „ì²´ ë§Œë“¤ê¸°(Hull Loft + Cabin)
with BuildPart() as ship:
    # â€”â€”â€” Hull
    # NOTE: loft()ëŠ” ì•ˆìª½ ê»ì§ˆë§Œ ë§Œë“¤ê¸° ë•Œë¬¸ì— "ë©´"ì´ ì—†ìŒ
    loft([bow, mid, stern], mode=Mode.ADD)

    # â€”â€”â€” Cabin (ì„ ì‹¤)
    # ë°•ìŠ¤ í¬ê¸°: ê¸¸ì´ 20%, í­ 40%, ë†’ì´ 40%
    cabin_length = length * 0.20
    cabin_width  = width  * 0.40
    cabin_height = height * 0.40
    cabin = Box(
            cabin_length,
            cabin_width,
            cabin_height,
            align=(Align.CENTER, Align.CENTER, Align.MIN),
        ).moved(Location((mid_x, 0, height)))  # ì¤‘ì•™(mid_x, 0) ìœ„, Z=height ì— ë°°ì¹˜

show(ship.part)